name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Tag again
        uses: kintoproj/kinto-github-actions/tag-docker-image@feat/docker-tag
        with:
          from_tag: nandiheath/test:12345
          to_tag: nandiheath/test:22345