name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: nandiheath/test:latest,'nandiheath/test:${{ env.GITHUB_SHA }}'
      -
        name: Tag again
        uses: kintoproj/kinto-github-actions/tag-docker-image@feat/docker-tag
        with:
          from_tag: nandiheath/test:latest
          to_tag: nandiheath/test:12345